#application.yml相比与application.properties更加简洁
#web容器相关配置
server:
  port: 8080
  address: 127.0.0.1

mybatis:
  mapper-locations: classpath:mappers/*.xml
#  扫描所有对应的数据表实体类Bean，多个package用逗号或者分号分隔
  type-aliases-package: com.lyp.springboot01.authmanage.model
  config-location: classpath:config/mybatis-config.xml

#数据库连接池
spring:
  datasource:
    username: root
    password: ENC(rZtEMVKyvFGWd0o8177Rwg==)
    url: jdbc:mysql://localhost:3306/springboot01?serverTimeZone=UTC&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
#    使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdel: 1

  freemarker:
    suffix: .ftl
    charset: UTF-8
    content-type: text/html
    template-loader-path: classpath:/templates/
     # freemarker模板后缀 默认是 .ftlh
     # 是否为此技术启用MVC视图分辨率。
#    enabled: true
#    check-template-location: true
    #设定所有request的属性在merge到模板的时候，是否要都添加到model中
#    expose-request-attributes: true
#    expose-session-attributes: true
    #指定requestContext属性的名
#    request-context-attribute: request
  mvc:
      static-path-pattern: /static/**

  redis:
    database: 0
#    host: 192.168.160.66
#    password: 123456
    host: 127.0.0.1
    port: 6379
    timeout: 30000


mail:
  smtp:
    auth: true
    port: 465
    timeout: 5000
  auth:
    name: zyx_2017@163.com
    password: HWbRmZ+rptL92fzX0C9itQyys+vNv34potaEYWXZdZM=

  transport:
    protocol: smtp
  send:
    charset: utf-8
  is:
    ssl: true
  host: smtp.163.com

#******************加解密相关配置*******************
#jasypt:
#    encrytor:
        #用来加解密的salt值
#        password:
        #用来使用新的算法，默认为org.jasypt.salt.NoOPIVGenerator,这样的话我们就无法使用命令行中生成的密文
#        ivGeneratorClassname: org.jasypt.salt.RandomIVGenerator





